# Site settings
title: CSSclasses
email: contact@cssconf.eu
description: "CSSclasses is for beginners and experts alike: Using CSS as a simple and low-barrier entry language, we empower people to understand their browser and to learn how to experiment with code. Workshop and hackathon in one event."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cssclasses.cssconf.eu"
twitter_username: cssclasses
github_username:  cssconf

# Build settings
markdown: kramdown
exclude: ['node_modules', 'css', '_scss']
keep_files: ['_site/css']
highlighter: pygments
permalink: pretty

gem: 'figure_image_tag'

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about.html
  - title: Coaches
    url: /coaches.html
  - title: Attendees
    url: /attendees.html
  - title: Learning Materials
    url: /materials.html
